<?php

use App\Http\Controllers\Admin\AnalyticsController as AdminAnalyticsController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\CommentController as AdminCommentController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\NotificationController as AdminNotificationController;
use App\Http\Controllers\Admin\PostController as AdminPostController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\EmailVerificationController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('home', [
        'latestPosts' => \App\Models\Post::published()->with(['user', 'tags'])->latest('published_at')->take(6)->get(),
        'popularTags' => \App\Models\Tag::withCount('posts')->orderByDesc('posts_count')->take(8)->get(),
    ]);
})->name('home');

/*
 * API documentation (Swagger UI). The spec itself is a static OpenAPI 3
 * document in public/openapi.json, regenerated by build-openapi.py — no extra
 * Composer package is needed to serve it.
 */
Route::view('/api/documentation', 'api.documentation')->name('api.documentation');
Route::get('/api/openapi.json', fn () => response()->file(public_path('openapi.json'), [
    'Content-Type' => 'application/json',
]))->name('api.openapi');

Route::get('/posts', [PostController::class, 'index'])->name('posts.index');

// Liveness probe used by an open article page so a removal is shown in place
// rather than discovered as a broken link. Cheap, public, read-only.
Route::get('/posts/{slug}/availability', [PostController::class, 'availability'])
    ->name('posts.availability');

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store']);

    Route::get('/register', [RegisteredUserController::class, 'create'])->name('register');
    Route::post('/register', [RegisteredUserController::class, 'store']);

    // Password reset (uses Laravel's Password broker + the existing password_reset_tokens table).
    Route::get('/forgot-password', [PasswordResetLinkController::class, 'create'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])->name('password.email');
    Route::get('/reset-password/{token}', [NewPasswordController::class, 'create'])->name('password.reset');
    Route::post('/reset-password', [NewPasswordController::class, 'store'])->name('password.update');
});

Route::middleware('auth')->group(function () {
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/dashboard/comments', [DashboardController::class, 'comments'])->name('dashboard.comments');

    /*
    | Email verification (Laravel's own flow).
    |
    | These three sit OUTSIDE the `verified` group on purpose — an unverified
    | user has to be able to reach the notice and ask for a new link.
    */
    Route::get('/email/verify', [EmailVerificationController::class, 'notice'])
        ->name('verification.notice');
    Route::get('/email/verify/{id}/{hash}', [EmailVerificationController::class, 'verify'])
        ->middleware(['signed', 'throttle:6,1'])
        ->name('verification.verify');
    Route::post('/email/verification-notification', [EmailVerificationController::class, 'send'])
        ->middleware('throttle:6,1')
        ->name('verification.send');

    /*
    | Writing content requires a verified address.
    |
    | Deliberately NARROW: reading, the member dashboard, notifications, logout
    | and deleting your own content all stay open to an unverified account, and
    | the admin area is not gated at all (an administrator is created by the
    | platform owner, not by self-registration). Only the actions that put new
    | public content on the site wait for the link to be opened.
    */
    Route::middleware('verified')->group(function () {
        // Must be registered before /posts/{post:slug} so "create" isn't matched as a slug.
        Route::get('/posts/create', [PostController::class, 'create'])->name('posts.create');
        Route::post('/posts', [PostController::class, 'store'])->name('posts.store');
        Route::get('/posts/{post:slug}/edit', [PostController::class, 'edit'])->name('posts.edit');
        Route::put('/posts/{post:slug}', [PostController::class, 'update'])->name('posts.update');
        // Publish your own draft without reopening the editor.
        Route::post('/posts/{post:slug}/publish', [PostController::class, 'publishOwn'])->name('posts.publish');

        Route::post('/posts/{post:slug}/comments', [CommentController::class, 'store'])->name('comments.store');
    });

    // Removing your own content is never blocked by verification.
    Route::delete('/posts/{post:slug}', [PostController::class, 'destroy'])->name('posts.destroy');
    Route::delete('/comments/{comment}', [CommentController::class, 'destroy'])->name('comments.destroy');

    // In-site notifications (bell). Database notifications on the current user.
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::post('/notifications/read-all', [NotificationController::class, 'readAll'])->name('notifications.readAll');
    Route::post('/notifications/{notification}/read', [NotificationController::class, 'read'])->name('notifications.read');
});

/*
|--------------------------------------------------------------------------
| Admin area
|--------------------------------------------------------------------------
| Every route below sits behind BOTH `auth` and the `admin` middleware, so a
| signed-in non-admin who types one of these URLs by hand receives a 403 —
| authorization is never left to a hidden menu item. Destructive and
| state-changing actions additionally go through PostPolicy / CommentPolicy /
| UserPolicy inside their controllers.
*/
Route::middleware(['auth', 'admin'])
    ->prefix('admin')
    ->name('admin.')
    ->group(function () {
        Route::get('/', [AdminDashboardController::class, 'index'])->name('dashboard');

        // Posts — "create" before the {post} wildcard.
        Route::get('/posts', [AdminPostController::class, 'index'])->name('posts.index');
        Route::get('/posts/create', [AdminPostController::class, 'create'])->name('posts.create');
        Route::post('/posts', [AdminPostController::class, 'store'])->name('posts.store');
        Route::post('/posts/{post}/restore', [AdminPostController::class, 'restore'])->name('posts.restore');
        // Article detail inside the dashboard (keeps the moderator in context).
        Route::get('/posts/{post}', [AdminPostController::class, 'show'])->name('posts.show');
        Route::get('/posts/{post}/edit', [AdminPostController::class, 'edit'])->name('posts.edit');
        Route::put('/posts/{post}', [AdminPostController::class, 'update'])->name('posts.update');
        Route::delete('/posts/{post}', [AdminPostController::class, 'destroy'])->name('posts.destroy');

        Route::post('/posts/{post}/publish', [AdminPostController::class, 'publish'])->name('posts.publish');
        Route::post('/posts/{post}/unpublish', [AdminPostController::class, 'unpublish'])->name('posts.unpublish');
        Route::post('/posts/{post}/schedule', [AdminPostController::class, 'schedule'])->name('posts.schedule');
        Route::post('/posts/{post}/cancel-schedule', [AdminPostController::class, 'cancelSchedule'])->name('posts.cancelSchedule');

        // Categories (== the project's tags: one system, not two). Fully
        // manageable by an administrator — add, rename, remove, sync defaults.
        Route::get('/categories', [AdminCategoryController::class, 'index'])->name('categories.index');
        Route::post('/categories', [AdminCategoryController::class, 'store'])->name('categories.store');
        // Restores only the categories ticked in the dialog (removed rows and
        // shipped defaults alike) — never everything at once.
        Route::post('/categories/restore', [AdminCategoryController::class, 'restore'])->name('categories.restore');
        Route::put('/categories/{category}', [AdminCategoryController::class, 'update'])->name('categories.update');
        Route::delete('/categories/{category}', [AdminCategoryController::class, 'destroy'])->name('categories.destroy');
        // Tags and categories are the same thing here; keep the URL working.
        Route::get('/tags', fn () => redirect()->route('admin.categories.index'))->name('tags.index');

        // Comments moderation.
        Route::get('/comments', [AdminCommentController::class, 'index'])->name('comments.index');
        // Bulk restore from the "removed comments" dialog. Declared before the
        // {comment} wildcard routes so "restore" is never read as an id.
        Route::post('/comments/restore', [AdminCommentController::class, 'restoreSelected'])->name('comments.restoreSelected');
        Route::post('/comments/{comment}/approve', [AdminCommentController::class, 'approve'])->name('comments.approve');
        Route::post('/comments/{comment}/hide', [AdminCommentController::class, 'hide'])->name('comments.hide');
        Route::post('/comments/{comment}/restore', [AdminCommentController::class, 'restore'])->name('comments.restore');
        Route::delete('/comments/{comment}', [AdminCommentController::class, 'destroy'])->name('comments.destroy');

        // Users.
        Route::get('/users', [AdminUserController::class, 'index'])->name('users.index');
        Route::get('/users/{user}', [AdminUserController::class, 'show'])->name('users.show');
        Route::put('/users/{user}/role', [AdminUserController::class, 'updateRole'])->name('users.role');
        Route::post('/users/{user}/toggle-active', [AdminUserController::class, 'toggleActive'])->name('users.toggleActive');

        // Analytics and notifications. (The platform-settings screen was removed.)
        Route::get('/analytics', [AdminAnalyticsController::class, 'index'])->name('analytics.index');
        Route::get('/notifications', [AdminNotificationController::class, 'index'])->name('notifications.index');
        Route::post('/notifications/read-all', [AdminNotificationController::class, 'readAll'])->name('notifications.readAll');
        Route::post('/notifications/{notification}/read', [AdminNotificationController::class, 'read'])->name('notifications.read');
    });

Route::get('/posts/{post:slug}', [PostController::class, 'show'])->name('posts.show');
